/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.thema.pixscape;

import com.vividsolutions.jts.geom.Geometry;
import java.io.File;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import org.geotools.data.shapefile.ShapefileDataStore;
import org.opengis.feature.simple.SimpleFeatureType;
import org.opengis.feature.type.AttributeType;

/**
 *
 * @author gvuidel
 */
public class PointShpPanel extends javax.swing.JPanel {

    /**
     * Creates new form PointShpPanel
     */
    public PointShpPanel() {
        initComponents();
    }

    public File getPointFile() {
        return pathSelectFilePanel.getSelectedFile();
    }
    
    public String getIdField() {
        return (String) idComboBox.getSelectedItem();
    }

    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled); 
        pathSelectFilePanel.setEnabled(enabled);
        idComboBox.setEnabled(enabled);
        jLabel1.setEnabled(enabled);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathSelectFilePanel = new org.thema.common.swing.SelectFilePanel();
        idComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        pathSelectFilePanel.setDescription("Shapefile");
        pathSelectFilePanel.setFileDesc("Shapefile");
        pathSelectFilePanel.setFileExts(".shp");
        pathSelectFilePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathSelectFilePanelActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pathSelectFilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pathSelectFilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pathSelectFilePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathSelectFilePanelActionPerformed
        try {
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            ShapefileDataStore datastore = new ShapefileDataStore(pathSelectFilePanel.getSelectedFile().toURI().toURL());
            SimpleFeatureType schema = datastore.getSchema();
            for(AttributeType type : schema.getTypes()) {
                if(!Geometry.class.isAssignableFrom(type.getBinding())) {
                    model.addElement(type.getName().getLocalPart());
                }
            }
            idComboBox.setModel(model);
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        }
    }//GEN-LAST:event_pathSelectFilePanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox idComboBox;
    private javax.swing.JLabel jLabel1;
    private org.thema.common.swing.SelectFilePanel pathSelectFilePanel;
    // End of variables declaration//GEN-END:variables
}
